export const tracks = [
  {
    id: 1,
    title: "Guilt",
    album: "Welcome Reality",
    time: "4:44",
    desc: "",
    authors: ["Nero"],
  },
  {
    id: 2,
    title: "Elektro",
    album: "Elektro",
    time: "2:22",
    desc: "",
    authors: ["Dynoro", "Outwork", "Mr. Gee"],
  },
  {
    id: 3,
    title: "I’m Fire",
    album: "I’m Fire",
    time: "2:22",
    desc: "",
    authors: ["Ali Bakgor"],
  },
  {
    id: 4,
    title: "Non Stop",
    album: "Non Stop",
    time: "4:12",
    desc: "Remix",
    authors: ["Стоункат", "Psychopath"],
  },
  {
    id: 5,
    title: "Run Run",
    album: "Run Run",
    time: "2:54",
    desc: "feat. AR/CO",
    authors: ["Jaded", "Will Clarke", "AR/CO"],
  },
  {
    id: 6,
    title: "Eyes on Fire",
    album: "Eyes on Fire",
    time: "5:20",
    desc: "Zeds Dead Remix",
    authors: ["Blue Foundation", "Zeds Dead"],
  },
  {
    id: 7,
    title: "Mucho Bien",
    album: "Mucho Bien",
    time: "3:41",
    desc: "Hi Profile Remix",
    authors: ["HYBIT", "Mr. Black", "Offer Nissim", "Hi Profile"],
  },
  {
    id: 8,
    title: "Knives n Cherries",
    album: "Captivating",
    time: "1:48",
    desc: "",
    authors: ["minthaze"],
  },
  {
    id: 9,
    title: "How Deep Is Your Love",
    album: "How Deep Is Your Love",
    time: "3:32",
    desc: "",
    authors: ["Calvin Harris", "Disciples"],
  },
  {
    id: 10,
    title: "Morena",
    album: "Soundz Made in Romania",
    time: "3:36",
    desc: "",
    authors: ["Tom Boxer"],
  },
];
